# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/caaeb9c0-c724-4a29-bdf0-8b9084050e91";
      fsType = "f2fs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/976f5f70-2c8b-497c-b885-bb98b833cf67";
      fsType = "f2fs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/9C5A-6125";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ee093cc1-6656-4f86-897a-8180ac57c1d0"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
